%%% backups.status = ok

%%% cluster1:alpha.example.com:webserver.status = ok
%%% cluster1:alpha.example.com:webserver.policy = daily
%%% cluster1:alpha.example.com:webserver.details = Everything OK!
%%% cluster1:alpha.example.com:webserver.secret = bzbzbz


%%% cluster1:bravo.example.com:webserver.status = err
%%% cluster1:bravo.example.com:webserver.policy = daily
%%% cluster1:bravo.example.com:webserver.details = Port 80 not listening
%%% cluster1:bravo.example.com:webserver.secret = bzbzbz


%%% cluster2:charlie.example.com:webserver.status = ok 
%%% cluster2:charlie.example.com:webserver.secret = bzbzbz

