# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAuthTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('ticket', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
