# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-14 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('machine', models.CharField(default='', max_length=100)),
                ('model_name', models.CharField(db_index=True, default='', max_length=100)),
                ('rid', models.CharField(db_index=True, default=None, max_length=100)),
                ('prid', models.CharField(default=None, max_length=100, null=True)),
                ('srid', models.CharField(db_index=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('value', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastupdate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc))),
                ('machine', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('netprocess', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
