{
    "ci": 0,
    "sendalert": false,
    "sendsummary": false,
    "nextsummary": 1517476380,
    "sumtime": 33180,
    "patrolled": 1649062407,
    "telegram_name": "",
    "telegram_chat_id": null,
    "last_motd": "b0e5e4382a3902123622dee450d782186f521e91",
    "training_stage": "basic:pingok",
    "partner_name": "demoisp",
    "partner_id": "1",
    "jargs": "{}",
    "email": "okerrdemo@maildrop.cc",
    "password": "pbkdf2_sha256$180000$SiOUWTgWwt0h$WTP0YwdgFnqOq0zu4VibQs2a9xKl6zxL0x8UlAOI1pk=",
    "first_name": "okerr2",
    "last_name": "demo",
    "last_login": 1649062436,
    "date_joined": 1502183635,
    "Membership": [
        {
            "groupname": "Cursa",
            "granted": 1582386143,
            "expires": null
        }
    ],
    "Project": [
        {
            "ci": 0,
            "name": "okerr demo",
            "created": 1649062407,
            "jkeys": "{\"lib\": {\"maxlogsz\": {\"030\": \"TAG maxlogsz\", \"050\": \"FILTER type==\\\"REG\\\"\", \"080\": \"LAST\", \"110\": \"FORMAT $size\", \"020\": \"METHOD numerical maxlim=10240000\", \"100\": \"DETAILS $basename is $sizeh bytes\", \"070\": \"SORT field=size\", \"040\": \"DIR path=/var/log\", \"010\": \"NAME $_name:maxlogsz\", \"060\": \"GREP field=basename re=\\\"\\\\.log$\\\"\", \"090\": \"KMGT field=size destfield=sizeh\"}, \"la\": {\"10\": \"NAME $_name:la\", \"30\": \"TAG la\", \"20\": \"METHOD numerical maxlim=1\", \"40\": \"LOADAVG period=2\"}, \"client_ip\": {\"0020\": \"METHOD string options=\\\"reinit dynamic\\\"\", \"0010\": \"NAME $_name:client_ip\", \"0030\": \"TAG client_ip\", \"0050\": \"STR $_client_ip\", \"0040\": \"MINVERSION 2.0.148\"}, \"du\": {\"0120\": \"KMGT\", \"0080\": \"FORK\", \"0070\": \"FILTER type=='DIR'\", \"0090\": \"NAME $_name:$basename\", \"0100\": \"DU path=$_dict_path\", \"0140\": \"LOAD size\", \"0110\": \"SAVE size\", \"0010\": \"SET DIR=/home\", \"0030\": \"METHOD numerical\", \"0130\": \"DETAILS\", \"0060\": \"DIR path=$DIR mindepth=1 maxdepth=1\", \"0050\": \"NAME $_name:du\"}, \"okerr_errors\": {\"10\": \"NAME $_name:okerr_errors\", \"30\": \"TAG okerr_errors\", \"20\": \"METHOD numerical\", \"40\": \"ERRORS\"}, \"mysql\": {\"30\": \"EXCEPT \\\"ERR\\\"\", \"20\": \"TAG db\", \"70\": \"EVAL $code == 0\", \"40\": \"RUN mysql --batch -N -u okerrtest -pokerrtestpass -e 'SELECT(1)'\", \"10\": \"NAME $_name:mysql\", \"50\": \"DETAILS $stderr\", \"60\": \"EXPORT code=code\"}, \"dfi\": {\"0020\": \"METHOD numerical maxlim=80\", \"0010\": \"NAME $_name:df\", \"0030\": \"TAG df\", \"0080\": \"NAME $_name-inodes-$path\", \"0070\": \"EXPORT path=path\", \"0100\": \"FORMAT $inodes_percent\", \"0060\": \"FORK\", \"0040\": \"DF\", \"0090\": \"DETAILS $inodes_percent% ($inodes_free inodes left)\", \"0050\": \"FILTER not ('/media/' in path or '/var/lib/docker' in path)\"}, \"get_google\": {\"30\": \"METHOD numerical maxlim=2\", \"20\": \"TAG http\", \"70\": \"FORMAT $elapsed\", \"40\": \"EXCEPT 999\", \"10\": \"NAME $_name:get_google\", \"50\": \"GETURL url=http://google.com timeout=2\", \"60\": \"DETAILS fetched in $elapsed seconds\"}, \"backups\": {\"0020\": \"# configuration\", \"0120\": \"FILTER mage<86400\", \"0080\": \"DIR path=$DIR maxdepth=2\", \"0070\": \"# script\", \"0160\": \"NAME $_name:backup:$tplname\", \"0150\": \"FORK\", \"0040\": \"SET RE=.gz$\", \"0090\": \"FILTER type==\\\"REG\\\"\", \"0100\": \"# Backup file monitoring\", \"0140\": \"GROUP key=tplname max=ctime\", \"0180\": \"FORMAT $size\", \"0110\": \"GREP field=basename re=$RE\", \"0010\": \"#\", \"0030\": \"SET DIR=/var/lib/okerr/backups\", \"0130\": \"REPLACE field=basename search=\\\"\\\\d{8}\\\" replace=DATE dest=tplname\", \"0170\": \"DETAILS $basename: $size bytes\", \"0060\": \"TAG backup\", \"0050\": \"METHOD numerical minlim=10240\"}, \"version\": {\"10\": \"NAME $_name:version\", \"30\": \"TAG version\", \"20\": \"METHOD heartbeat\", \"40\": \"VERSION\"}, \"uptime\": {\"030\": \"TAG uptime\", \"050\": \"SAVE uptimesec\", \"080\": \"LOAD uptimesec\", \"020\": \"METHOD numerical diffmin=0\", \"070\": \"DETAILS\", \"040\": \"UPTIME\", \"010\": \"NAME $_name:uptime\", \"060\": \"DHMS\"}, \"opentcp\": {\"030\": \"TAG opentcp\", \"050\": \"FILTER status==\\\"LISTEN\\\" and ((proto==\\\"TCP\\\" and ip==\\\"0.0.0.0\\\") or ((proto==\\\"TCP6\\\" and ip==\\\"::\\\")))\", \"080\": \"SORT field=port\", \"110\": \"DETAILS $_str\", \"020\": \"METHOD string options=\\\"reinit dynamic text\\\"\", \"100\": \"STR\", \"070\": \"GROUP key=port\", \"040\": \"CONNECTIONS\", \"010\": \"NAME $_name:opentcp\", \"060\": \"FILTER basename!=\\\"smtpd\\\" and basename!=\\\"pop3-login\\\"\", \"090\": \"FORMAT $port($basename)\"}, \"df\": {\"0020\": \"METHOD numerical maxlim=80\", \"0010\": \"NAME $_name:df\", \"0030\": \"TAG df\", \"0080\": \"NAME $_name-$path\", \"0070\": \"EXPORT path=path\", \"0100\": \"FORMAT $percent\", \"0060\": \"FORK\", \"0040\": \"DF\", \"0090\": \"DETAILS $percent% ($usedg/${totalg}G used, $freeg left)\", \"0050\": \"FILTER not ('/media/' in path or '/var/lib/docker' in path)\"}, \"ping_google\": {\"30\": \"METHOD numerical maxlim=1\", \"20\": \"TAG ping\", \"40\": \"EXCEPT 999\", \"10\": \"NAME $_name:ping_google\", \"50\": \"PING host=google.com timeout=1000 count=3\", \"60\": \"FORMAT $packet_lost\"}}, \"mylib\": {}, \"servers\": {}, \"conf\": {\"anyserver\": {\"@include lib:myip\": \"\", \"@include lib:df\": \"\", \"@include lib:version\": \"\", \"@include lib:dfi\": \"\", \"@include lib:uptime\": \"\", \"@include lib:opentcp\": \"\", \"@include lib:maxlogsz\": \"\", \"@include lib:la\": \"\"}}, \"@access\": {\"client\": \"\"}}",
            "limited": false,
            "partner_access": true,
            "Policy": [
                {
                    "ci": 0,
                    "name": "Default",
                    "period": "3600s",
                    "patience": "1200s",
                    "autocreate": true,
                    "secret": "",
                    "smtpupdate": true,
                    "httpupdate": true,
                    "retry_schedule": "",
                    "recovery_retry_schedule": "",
                    "reduction": "0",
                    "url_statuschange": "",
                    "PolicySubnet": [
                        {
                            "subnet": "0.0.0.0/0",
                            "remark": "IPv4 world access (default)"
                        },
                        {
                            "subnet": "::/0",
                            "remark": "IPv6 world access (default)"
                        }
                    ]
                },
                {
                    "ci": 0,
                    "name": "Daily",
                    "period": "86400s",
                    "patience": "7200s",
                    "autocreate": true,
                    "secret": "",
                    "smtpupdate": true,
                    "httpupdate": true,
                    "retry_schedule": "30 600",
                    "recovery_retry_schedule": "",
                    "reduction": "0",
                    "url_statuschange": "",
                    "PolicySubnet": [
                        {
                            "subnet": "0.0.0.0/0",
                            "remark": "IPv4 world access (default)"
                        },
                        {
                            "subnet": "::/0",
                            "remark": "IPv6 world access (default)"
                        }
                    ]
                }
            ],
            "ProjectMember": [
                {
                    "email": "okerrdemo@maildrop.cc",
                    "iadmin": true,
                    "tadmin": true
                }
            ],
            "ProjectTextID": [
                {
                    "textid": "okerrdemo"
                },
                {
                    "textid": "okerrdemo2"
                }
            ],
            "Indicator": [
                {
                    "policy": "Default",
                    "cm": "dnsbl",
                    "ci": 0,
                    "name": "antispam:gmail.com",
                    "desc": "",
                    "_status": "ERR",
                    "prevstatus": "OK",
                    "details": "dnsbl.sorbs.net, spam.dnsbl.sorbs.net (total: 2/52)",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "alpha@moscow.ru",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"extra\": \"\", \"host\": \"mail-wr1-f54.google.com\", \"skip\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "dnsbl",
                    "ci": 0,
                    "name": "antispam:ngs.ru",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "Not found in 52 DNSBL checked",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"asdf\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"extra\": \"\", \"host\": \"smtpout24.ngs.ru\", \"skip\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "dnsbl",
                    "ci": 0,
                    "name": "antispam:yandex.ru",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "Not found in 52 DNSBL checked",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"extra\": \"\", \"host\": \"forward104o.mail.yandex.net\", \"skip\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "whois",
                    "ci": 0,
                    "name": "domains:google.com",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "",
                    "details": "2354 days left",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"domain\": \"google.com\", \"days\": \"30\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "whois",
                    "ci": 0,
                    "name": "domains:okerr.com",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "",
                    "details": "877 days left",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"domain\": \"okerr.com\", \"days\": \"30\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "sslcert",
                    "ci": 0,
                    "name": "mail:yandex.ru:imaps",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "143 days left",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"imap.yandex.ru\", \"options\": \"\", \"port\": \"993\", \"days\": \"20\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "tcpport",
                    "ci": 0,
                    "name": "mail:yandex.ru:smtp",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "Connected to mx.yandex.ru:25 at 77.88.21.249",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"substr\": \"\", \"host\": \"mx.yandex.ru\", \"port\": \"25\"}",
                    "location": "charlie@falkenstein.de"
                },
                {
                    "policy": "Default",
                    "cm": "sslcert",
                    "ci": 0,
                    "name": "mail:yandex.ru:smtps",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "119 days left",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"smtp.yandex.ru\", \"days\": \"20\", \"options\": \"\", \"port\": \"465\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:backups:DATE-charlie.okerr.com.tar.gz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "20220323-charlie.okerr.com.tar.gz: 4.4K",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"backups\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"4491.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"\", \"diffmin\": \"0\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:backups:DATE-golf.okerr.com.tar.gz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "20220323-golf.okerr.com.tar.gz: 107.2K",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"backups\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"109803.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"10k\", \"maxlim\": \"\", \"diffmin\": \"0\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:df-/",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "66.77%, 18.8G/28.2G used, 8.2G free",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"df\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"66.77\", \"maxlim\": \"80\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:df-/boot",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "79.05%, 49.8M/62.9M used, 13.2M free",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"df\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"79.05\", \"maxlim\": \"85\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:google",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:la",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.13",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"la\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"0.13\", \"maxlim\": \"1\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:la5",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.25",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"la\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.25\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"2\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:maxfilesz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "/var/log/auth.log 30.9M",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"maxfilesz\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"32450447.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"100M\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:one1111",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:oneoneoneone",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "string",
                    "ci": 0,
                    "name": "pi2:opentcp",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "111:systemd 22:sshd 25:master 53:connmand 6379:redis-server 80:nginx 8888:tinyproxy (0 fails)",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"opentcp\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"patience\": \"\", \"secret\": \"\", \"options\": \"reinit dynamic text\", \"str\": \"22 25 53 80 111 6379 8888\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:temp",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "51002",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"51002.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi2:uptime",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "33d 13h 31m 54s",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"uptime\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"0\", \"current\": \"2899914.0\", \"maxlim\": \"\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "string",
                    "ci": 0,
                    "name": "pi2:version",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "1.2.73",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"version\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"str\": \"1.2.73\", \"patience\": \"\", \"secret\": \"\", \"options\": \"reinit dynamic\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:backups:DATE-charlie.okerr.com.tar.gz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "20220323-charlie.okerr.com.tar.gz: 4.4K",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"backups\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"4491.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"\", \"diffmin\": \"0\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:backups:DATE-golf.okerr.com.tar.gz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "20220323-golf.okerr.com.tar.gz: 107.2K",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"backups\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"109803.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"10k\", \"maxlim\": \"\", \"diffmin\": \"0\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:df-/",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "66.77%, 18.8G/28.2G used, 8.2G free",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"df\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"66.77\", \"maxlim\": \"80\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:df-/boot",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "79.05%, 49.8M/62.9M used, 13.2M free",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"df\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"79.05\", \"maxlim\": \"85\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:google",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:la",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.13",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"la\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"\", \"current\": \"0.13\", \"maxlim\": \"1\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:la5",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.24",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"la\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.24\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"2\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:maxfilesz",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "/var/log/auth.log 30.9M",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"maxfilesz\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"32448810.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"100M\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:one1111",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:oneoneoneone",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "0.0",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"0.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"0\", \"maxlim\": \"0\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "string",
                    "ci": 0,
                    "name": "pi:opentcp",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "111:systemd 22:sshd 25:master 53:connmand 6379:redis-server 80:nginx 8888:tinyproxy (0 fails)",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"opentcp\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"patience\": \"\", \"secret\": \"\", \"options\": \"reinit dynamic text\", \"str\": \"22 25 53 80 111 6379 8888\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:temp",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "50464",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"run\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"current\": \"50464.0\", \"patience\": \"\", \"secret\": \"\", \"minlim\": \"\", \"maxlim\": \"\", \"diffmin\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "numerical",
                    "ci": 0,
                    "name": "pi:uptime",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "33d 13h 31m 34s",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"uptime\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"secret\": \"\", \"minlim\": \"\", \"diffmin\": \"0\", \"current\": \"2899894.0\", \"maxlim\": \"\", \"patience\": \"\", \"diffmax\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "string",
                    "ci": 0,
                    "name": "pi:version",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "1.2.73",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"version\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"str\": \"1.2.73\", \"patience\": \"\", \"secret\": \"\", \"options\": \"reinit dynamic\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "ping",
                    "ci": 0,
                    "name": "ping:1111",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "51.87 ms",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"1.1.1.1\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "ping",
                    "ci": 0,
                    "name": "ping:BAD",
                    "desc": "\u041d\u0430\u043c\u0435\u0440\u0435\u043d\u043d\u043e \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 IP \u0430\u0434\u0440\u0435\u0441. \u042d\u0442\u043e\u0442 \u0438\u043d\u0434\u0438\u043a\u0430\u0442\u043e\u0440 \u0438 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u0432 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0438 ERR (\u0434\u043b\u044f \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f).",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "50.00 ms",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"8.8.8.9\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "ping",
                    "ci": 0,
                    "name": "ping:yandex.ru",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "50.11 ms",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"yandex.ru\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "httpstatus",
                    "ci": 0,
                    "name": "sites:okerr.com",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "ERR",
                    "details": "Got status code 200 OK as expected",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[\"demo\"]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"url\": \"https://okerr.com/\", \"status\": \"200\", \"secret\": \"\"}",
                    "location": ""
                },
                {
                    "policy": "Default",
                    "cm": "sslcert",
                    "ci": 0,
                    "name": "sites:ssl:okerr.com",
                    "desc": "",
                    "_status": "OK",
                    "prevstatus": "",
                    "details": "75 days left",
                    "created": 1649062407,
                    "maintenance": null,
                    "dead": false,
                    "disabled": false,
                    "silent": false,
                    "problem": false,
                    "last_fail_machine": "",
                    "jtags": "[]",
                    "jiargs": "{}",
                    "jcheckargs": "{\"host\": \"www.okerr.com\", \"days\": \"20\", \"options\": \"\", \"port\": \"443\"}",
                    "location": ""
                }
            ],
            "ProjectInvite": [],
            "StatusPage": [
                {
                    "addr": "first",
                    "title": "first",
                    "public": false,
                    "can_subscribe": false,
                    "desc": "",
                    "StatusIndicator": [],
                    "StatusBlog": [],
                    "StatusSubscription": []
                }
            ],
            "DynDNSRecord": [],
            "ProjectAccessKey": []
        }
    ],
    "ProfileArg": [
        {
            "name": "_price",
            "value": 4500,
            "expires": null,
            "visible": true
        },
        {
            "name": "maxindicators",
            "value": 102,
            "expires": null,
            "visible": true
        },
        {
            "name": "maxprojects",
            "value": 3,
            "expires": null,
            "visible": true
        },
        {
            "name": "settextname",
            "value": 1,
            "expires": null,
            "visible": true
        },
        {
            "name": "teamsize",
            "value": 5,
            "expires": null,
            "visible": true
        },
        {
            "name": "login",
            "value": 1,
            "expires": null,
            "visible": true
        },
        {
            "name": "minperiod",
            "value": 1200,
            "expires": null,
            "visible": true
        },
        {
            "name": "minperiod:30",
            "value": 2,
            "expires": null,
            "visible": true
        },
        {
            "name": "maxstatus",
            "value": 5,
            "expires": null,
            "visible": true
        },
        {
            "name": "maxdyndns",
            "value": 5,
            "expires": null,
            "visible": true
        },
        {
            "name": "status_maxsubscribers",
            "value": 1000,
            "expires": null,
            "visible": true
        }
    ],
    "BonusActivation": [],
    "Oauth2Binding": [
        {
            "provider": "demoisp",
            "uid": "okerrdemo@maildrop.cc"
        }
    ]
}
