# Generated by Django 2.2.1 on 2019-05-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrecord',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='alertrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonusactivation',
            name='BonusCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='okerrui.BonusCode'),
        ),
        migrations.AlterField(
            model_name='bonusactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonuscode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='checkarg',
            name='cm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.CheckMethod'),
        ),
        migrations.AlterField(
            model_name='dyndnsrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='dyndnsrecordvalue',
            name='ddr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='okerrui.DynDNSRecord'),
        ),
        migrations.AlterField(
            model_name='dyndnsrecordvalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='grouparg',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='iarg',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='iarg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ichange',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.CheckMethod'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Policy'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Profile'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='policysubnet',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Policy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilearg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='profilearg',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='projecttextid',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='statusblog',
            name='status_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.StatusPage'),
        ),
        migrations.AlterField(
            model_name='statusindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Indicator'),
        ),
        migrations.AlterField(
            model_name='statusindicator',
            name='status_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.StatusPage'),
        ),
        migrations.AlterField(
            model_name='statuspage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.Project'),
        ),
        migrations.AlterField(
            model_name='statussubscription',
            name='status_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okerrui.StatusPage'),
        ),
    ]
