# Generated by Django 2.2.1 on 2019-10-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0002_auto_20190526_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policysubnet',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Policy'),
        ),
    ]
