# Generated by Django 3.0.2 on 2020-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0002_oauth2binding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2binding',
            name='uid',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='oauth2binding',
            unique_together={('profile', 'provider')},
        ),
    ]
