# Generated by Django 3.0.2 on 2020-02-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0003_auto_20200214_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='wipe',
        ),
    ]
