# Generated by Django 3.0.2 on 2020-02-21 20:04

from django.db import migrations, models


def set_group_names(apps, schema_editor):
    Membership = apps.get_model('okerrui', 'Membership')

    for m in Membership.objects.all():
        m.groupname = m.group.name
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0004_remove_policy_wipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='groupname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(set_group_names),
    ]
