# Generated by Django 2.2.1 on 2019-10-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0004_auto_20191023_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Profile'),
        ),
    ]
