# Generated by Django 2.2.1 on 2019-10-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0005_auto_20191023_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilearg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='okerrui.Group'),
        ),
        migrations.AlterField(
            model_name='profilearg',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Profile'),
        ),
    ]
