# Generated by Django 3.0.2 on 2020-02-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0005_membership_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
    ]
