# Generated by Django 3.0.2 on 2020-02-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0006_remove_membership_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilearg',
            name='group',
        ),
    ]
