# Generated by Django 3.0.2 on 2020-02-25 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0008_remove_membership_refilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusblog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
