# Generated by Django 2.2.1 on 2019-10-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0008_auto_20191024_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusactivation',
            name='BonusCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='okerrui.BonusCode'),
        ),
        migrations.AlterField(
            model_name='bonusactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonuscode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Group'),
        ),
    ]
