# Generated by Django 2.2.1 on 2019-11-21 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0009_auto_20191024_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndnsrecord',
            name='nfails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dyndnsrecord',
            name='scheduled',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
