# Generated by Django 3.0.2 on 2020-03-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0010_auto_20200323_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusactivation',
            old_name='text',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='bonusactivation',
            name='user',
        ),
        migrations.AddField(
            model_name='bonusactivation',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='okerrui.Profile'),
            preserve_default=False,
        ),
    ]
