# Generated by Django 3.0.2 on 2020-03-24 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0011_auto_20200324_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusactivation',
            name='activated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
