# Generated by Django 2.2.1 on 2019-12-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0011_projectaccesskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaccesskey',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='projectaccesskey',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='projectaccesskey',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='projectaccesskey',
            name='trans_last_sync',
        ),
        migrations.RemoveField(
            model_name='projectaccesskey',
            name='trans_last_update',
        ),
    ]
