# Generated by Django 3.0.2 on 2020-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0012_auto_20200324_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusactivation',
            name='verification_failed_since',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
