# Generated by Django 2.2.1 on 2019-12-09 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0012_auto_20191203_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='expected',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
