# Generated by Django 3.0.2 on 2020-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0013_bonusactivation_verification_failed_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jargs',
            field=models.TextField(default='{}'),
        ),
    ]
