# Generated by Django 2.2.1 on 2019-12-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0013_auto_20191209_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecord',
            name='reduction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
