# Generated by Django 2.2.1 on 2019-12-23 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0014_alertrecord_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecord',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='policy',
            name='reduction_schedule',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
