# Generated by Django 3.0.2 on 2020-10-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0014_profile_jargs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dyndnsrecord',
            unique_together={('hostname', 'domain')},
        ),
    ]
