# Generated by Django 2.2.1 on 2019-12-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0015_auto_20191223_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='reduction_schedule',
            new_name='reduction',
        ),
    ]
