# Generated by Django 3.0.2 on 2020-10-01 13:46

from okerrui.models import DynDNSRecord
from django.db import migrations, models


def set_name(apps, schema_editor):

    if schema_editor.connection.alias != 'default':
        return

    DynDNSRecord = apps.get_model('okerrui', 'DynDNSRecord')
    
    counter = 0

    print("DynDNSRecord:", type(DynDNSRecord), DynDNSRecord)
    for ddr in DynDNSRecord.objects.all():
        ddr.name = "{}.{}".format(ddr.hostname, ddr.domain)
        print(ddr.name)
        ddr.save()    
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0015_auto_20201001_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyndnsrecord',
            name='name',
            field=models.CharField(default='www', max_length=200),
        ),
        migrations.RunPython(set_name)
    ]
