# Generated by Django 3.0.7 on 2020-11-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0016_dyndnsrecord_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('trans_last_update', models.DateTimeField(default=None, null=True)),
                ('trans_last_sync', models.DateTimeField(default=None, null=True)),
                ('rid', models.CharField(db_index=True, default='', max_length=100)),
                ('ci', models.IntegerField(db_index=True, default=0)),
                ('value', models.CharField(default='', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='okerrui.Indicator')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okerrui.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
