# Generated by Django 3.0.2 on 2020-02-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okerrui', '0016_auto_20191223_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('name', 'project')},
        ),
    ]
