# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
